import type { Copy } from "./types";

export const en: Copy = {
  meta: {
    homeTitle: "Home | Prime 6 High performing charcoal and wood logs",
    homeDescription:
      "Prime 6 is proud to power some of the best restaurants in the country. From Josper and MiBrassa ovens to wood burning open grills, we reduce costs, increase efficiencies and help Hospitality have a positive impact on the environment.",
    whyTitle: "Why Prime 6 | Prime 6",
    whyDescription:
      "Learn how our products can reduce your costs in operating a live fire kitchen while increasing your teams efficiencies. Save money, work better and do good.",
    aboutTitle: "About | Prime 6",
    aboutDescription:
      "Prime 6 is proud to power some of the best restaurants in the country. From Josper and MiBrassa ovens to wood burning open grills, we reduce costs, increase efficiencies and help Hospitality have a positive impact on the environment.",
    grillersTitle: "Home Grillers | Prime 6",
    chefsTitle: "Pro Chefs | Prime 6",
    chefsDescription:
      "Everywhere fire is used. From your Josper or MiBrassa to your Pizza ovens and wood burning grills. Prime 6 will work anywhere food is cooked over a flame.",
    sampleTitle: "Get a sample | Prime 6",
    sampleDescription:
      "Foodservice and Hospitality businesses can receive a free sample of Prime 6 to try out. Fill out the form and we will send you a sample.",
    terryTitle: "Terry Koval | Prime 6",
    newsTitle: "In The News | Prime 6",
    newsDescription:
      "See how Prime 6 founders closed the deal with Shark Kevin O'Leary on season 12 episode 6",
    sustainTitle: "Sustainability Dashboard | Prime 6",
    contactTitle: "Contact | Prime 6",
    contactDescription:
      "Any questions about Prime 6 products? Leave us a message and we will get back to you.",
  },
  chrome: {
    openMenu: "Open menu",
    closeMenu: "Close menu",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    sampleCta: "Request a Hospitality Sample",
    builtBy: "Built by dglxss",
    stayInTouch: "Stay in touch",
    subscribe: "Subscribe",
    subscribeThanks: "Thanks! We'll keep in touch",
    emailPlaceholder: "add you email here",
    join: "Want to join the team?",
    apply: "APPLY",
    footerNote: "PRIME 6",
  },
  nav: {
    home: "Home",
    grillers: "Home Grillers",
    why: "Why Prime 6",
    chefs: "Pro Chefs",
    about: "About",
    biochar: "Biochar",
    sample: "Get a Sample",
    news: "Shark Tank and News",
    sustainability: "Sustainability Dashboard",
    contact: "Contact us",
  },
  hero: {
    tagline: ["More heat", "less waste", "bigger savings"],
    cta: "Request a Hospitality Sample",
    description: "High performing charcoal and wood logs",
    heading: ["Chef-Tested", "Fire", "Perfected"],
    stats: [
      { value: "60", unit: "%", kicker: "Up to", label: "Fuel\ncosts" },
      { value: "22", unit: "LB", label: "All usable\nno waste" },
      { value: "1", unit: "", label: "Tree per case\nwith Veritree" },
    ],
  },
  proof: [
    {
      label: "USDA Certified",
      detail: "USDA-certified products",
      href: "/about#usda",
    },
    {
      label: "Woman-owned",
      detail: "Woman owned U.S. business",
      href: "/about",
    },
    {
      label: "Avendra",
      detail: "Avendra approved",
      href: "/#avendra",
    },
    {
      label: "Shark Tank",
      detail: "Season 12 episode 6 · Kevin O'Leary",
      href: "/shark-tank",
    },
    {
      label: "Veritree",
      detail: "One tree per case",
      href: "https://impact.veritree.com/prime6",
      external: true,
    },
    {
      label: "Chef Terry Koval",
      detail: "James Beard Award Winner Best Chef South East",
      href: "/terry-koval",
    },
    {
      label: "Chef Grant Achatz",
      detail: "Alinea",
      href: "/#chefs",
    },
  ],
  burn: {
    kicker: "The prime 6 difference",
    title: "Density. Process. Results.",
    beats: [
      {
        label: "01",
        title: "Density",
        body: [
          "It all starts with the raw material.",
          "We upcycle wood waste to reduce tree-cutting and waste in hospitality.",
          "Instead of random wood with unpredictable density, we compress sawdust into ultra-dense logs—no chemicals, no glues, no additives. Just one ingredient: hardwood.",
          "3X denser than wood, with no air pockets or moisture, delivering the consistency needed for high performance.",
        ],
        image: "/media/bark.jpg",
        alt: "Tree bark",
      },
      {
        label: "02",
        title: "Process",
        body: [
          "Precision matters.",
          "Prime 6 uses advanced furnaces to control time, temperature, and oxygen levels, ensuring a precise process with uniform raw materials. This maximizes efficiency and achieves the highest carbon content without sacrificing density. More carbon = better performance.",
          "Every piece of P6 charcoal is the same high quality—no unusable pebbles, no under-carbonized chunks. Just pure, consistent fuel.",
        ],
        image: "/media/charcoal.jpg",
        alt: "Prime 6 charcoal",
      },
      {
        label: "03",
        title: "Results",
        body: [
          "Proudly powering live fire everywhere.",
          "Prime 6 is proud to power some of the best restaurants in the country. From Josper and MiBrassa ovens to wood burning open grills, we reduce costs, increase efficiencies and help Hospitality have a positive impact on the environment.",
          "Reliability in every log. Whether charcoal or wood, Prime 6 delivers the same performance—every time.",
        ],
        image: "/media/pizza.jpg",
        alt: "pizza closeup.jpg",
      },
    ],
  },
  whyHome: {
    kicker: "Why Prime 6?",
    title: "Engineered to perform",
    lead: "More heat, less waste, bigger savings.",
    body: [
      "Prime 6 burns hotter, lasts longer, and cuts fuel costs by up to 60%.",
      "Engineered for efficiency, our charcoal delivers consistent performance with no waste—just pure, high-carbon hardwood. Less refilling, predictable costs, and better results.",
    ],
    mission:
      "We are a mission driven company, woman owned, USDA Certified and a partner to the biggest reforestation organization in the world.",
    link: "See why chefs choose Prime 6",
  },
  audiences: {
    kicker: "Who are we for?",
    title: "Who are we for?",
    hospitality: "Hospitality Professionals",
    hospitalityBody:
      "From Josper and MiBrassa ovens to wood burning open grills, we reduce costs, increase efficiencies and help Hospitality have a positive impact on the environment.",
    pit: "Pit Masters & Pro Home Grillers",
    pitBody:
      "For the home pitmaster who treats every cook like a craft, Prime 6 delivers the performance you need to grill and smoke like a pro.",
  },
  economics: {
    id: "calculator",
    kicker: "Spend Less. Work easier. Profit more.",
    title: "How does Prime 6 reduce costs?",
    fuelQuestion: "What fuels do you currently use?",
    fuels: ["Charcoal", "Wood", "Both"],
    weekly: "Weekly LBs",
    weeklyHint: "Operations using charcoal see a significant drop in weekly LBs purchased.",
    hours: "Hours on a current load",
    hoursHint: "Your figure. Prime 6 burn time below is the published performance, not a multiplier.",
    refills: "Refills per service",
    refillsHint: "Burns hotter, lasts longer – fewer refills per service.",
    ceiling: "Published ceiling",
    ceilingHint: "Cuts fuel costs by up to 60%. The slider stops at that ceiling.",
    estimate: "Are you paying for pounds or performance?",
    estimateBody:
      "You use significantly fewer pounds of solid fuel, so even with a slightly higher per-pound cost, the overall monthly savings are substantial. Figures below are relative units at the ceiling you set.",
    traditional: "Current fuel",
    traditionalSub: "Pounds, hours, and refills you entered",
    ceilingCard: "Up to 60%",
    ceilingSub: "Published ceiling. Not a dollar estimate.",
    withPrime: "With Prime 6",
    withSub: "Relative units inside the published ceiling",
    lbs: "LB / week",
    refillsUnit: "Refills",
    hoursUnit: "Hours you entered",
    equivalence: "1LB of Prime 6 = 3LBs of regular charcoal",
    woodNote:
      "With wood, the impact is even greater—many cut wood use by 40-60%, some up to 80%, when supplementing embers with P6. This calculator does not go past the published “up to 60%” ceiling.",
    burnPublished: "Prime 6 provides a steady, consistent heat for 5+ hours with low ash and a clean burn.",
    smokerPublished: "Lasting over 14 hours in a smoker with steady, reliable heat.",
    disclaimer: [
      "Prime 6 burns hotter, lasts longer, and cuts fuel costs by up to 60%.",
      "The values displayed are approximate and may not accurately represent specific or localized conditions. Prime 6 does not guarantee the accuracy, reliability, or completeness of the data and disclaims any liability for decisions made based on this information.",
    ],
    noDollars: "Sold by the LB, not the cord — full cost transparency. Relative units only.",
  },
  chefsBlock: {
    kicker: "Simply put",
    title: "What the pros are saying",
    terryName: "Chef Terry Koval",
    terryAward: "James Beard Award Winner",
    terryRole: "Chef owner - Dear and the Dove",
    terryBody:
      "Listen to Chef Terry Koval, James Beard Award Winner Best Chef South East, explain in a simple and direct way why his hearth run on Prime 6 Charcoal.",
    interview: "View the full interview",
    pros: "What the pros are saying",
    chefs: [
      { name: "Chef Grant Achatz, Alinea", image: "/media/grant.jpg", alt: "Chef Grant Achatz, Alinea" },
      { name: "Chef John Um, Sushi Samba", image: "/media/john-um.jpg", alt: "Chef John Um, Sushi Samba" },
      { name: "Chef John Tesar, Knife", image: "/media/john-tesar.jpg", alt: "Chef John Tesar, Knife" },
      {
        name: "Chef Gary Francis Xavier LaMorte, Honest",
        image: "/media/gary.jpg",
        alt: "Chef Gary Francis Xavier LaMorte, Honest",
      },
      {
        name: "Chef Brian Howard, Owner of Sparrow + WOLF",
        image: "/media/brian.jpg",
        alt: "Chef Brian Howard, Owner of Sparrow + WOLF",
      },
      {
        name: "Celebrity Chef Michael Simon",
        image: "/media/simon.jpg",
        alt: "Celebrity Chef Michael Simon",
      },
      {
        name: "Chef Hugh Mangum, Partner @Mighty Quinn's BBQ",
        image: "/media/hugh.jpg",
        alt: "Chef Hugh Mangum, Partner @Mighty Quinn's BBQ",
      },
      {
        name: "Gentle Giant Brewing Company",
        image: "/media/gentle.jpg",
        alt: "Gentle Giant Brewing Company",
      },
    ],
  },
  sampleBand: {
    title: "Get a FREE Sample",
    body: "Samples available only for professionals in the hospitality or procurement industry.",
    cta: "GET SAMPLE",
  },
  whyClose: {
    title: "Efficient. Predictable. Cost-saving.",
    bottom:
      "Bottom line. You use significantly fewer pounds of solid fuel, so even with a slightly higher per-pound cost, the overall monthly savings are substantial.",
  },
  whyPage: [
    {
      id: "transparency",
      title: "Transparency and consistency",
      paragraphs: [
        "At the end of the day, it’s about cost reduction.",
        "Our dense, carbon-rich charcoal burns hotter and longer, reducing the amount needed. Operations using charcoal see a significant drop in weekly LBs purchased.",
        "With wood, the impact is even greater—many cut wood use by 40-60%, some up to 80%, when supplementing embers with P6. Sold by the LB, not the cord, P6 gives you full cost transparency.",
        "Some pizza kitchens have it down to a science, adding 1 log every XX minutes to keep ovens at temp. This not only ensures cost control but also simplifies training.",
        "Predictable fuel costs—no matter who’s on the line.",
      ],
    },
    {
      id: "pebbles",
      title: "Are you paying for air and pebbles?",
      paragraphs: [
        "Traditional lump charcoal comes with built-in waste.",
        "When you buy by weight, you pay for everything—big chunks, small pieces, and dust.",
        "Anything under 1.5 inches adds no real heat or longevity, often burning out before your grill or oven is even ready.",
        "Waste can range from 5% to 35%, meaning the more small pieces in your bag, the more you're actually paying per usable pound.",
        "If half your bag is dust, you’re paying double.",
        "With Prime 6, you use the full 22LB—no dust, no pebbles, no waste. Just pure charcoal.",
      ],
    },
    {
      id: "value",
      title: "Value. Performance. Efficiency.",
      paragraphs: [
        "High performance should not come at the expense of high costs.",
        "More heat, less fuel, lower costs.",
        "Our high heat and long burn time mean you use less wood or charcoal per service.",
        "We’re not here to replace your wood—we’re here to supplement your embers.",
        "Prime 6 provides a steady, consistent heat for 5+ hours with low ash and a clean burn, saving you money every step of the way.",
      ],
    },
    {
      id: "density",
      title: "Density",
      paragraphs: [
        "It all starts with the raw material.",
        "Instead of random wood with unpredictable density, we compress sawdust into ultra-dense logs—no chemicals, no glues, no additives.",
        "Just one ingredient: hardwood.",
        "3X denser than wood, with no air pockets or moisture, delivering the consistency needed for high performance.",
      ],
    },
    {
      id: "process",
      title: "Process",
      paragraphs: [
        "Precision matters.",
        "Traditional charcoal production is unpredictable—different wood sizes and densities lead to inconsistent results.",
        "Prime 6 uses advanced furnaces to control time, temperature, and oxygen levels, ensuring a precise process with uniform raw materials. This maximizes efficiency and achieves the highest carbon content without sacrificing density. More carbon = better performance.",
        "Every piece of P6 charcoal is the same high quality—no unusable pebbles, no under-carbonized chunks. Just pure, consistent fuel.",
      ],
    },
    {
      id: "results",
      title: "Results",
      paragraphs: [
        "Reliability in every log.",
        "Whether charcoal or wood, Prime 6 delivers the same performance—every time.",
        "Once you dial in your setup, P6 burns predictably. In a pizza oven, one log every X minutes maintains steady heat daily.",
        "On a grill, Mibrasa, hearth, or any equipment, it provides consistent results. No fire management, no constant replenishing, no guesswork.",
        "Just consistency you can count on.",
      ],
    },
    {
      id: "pounds",
      title: "Are you paying for pounds or performance?",
      paragraphs: [
        "Charcoal quality comes down to two things: raw material and carbonization.",
        "With lump charcoal, you can’t control the wood species, density, or size—so the carbonization process applies the same heat to uneven pieces, like roasting a prime rib and a filet together. One gets overcooked, the other undercooked.",
        "At Prime 6, we engineer our charcoal. We extrude sawdust into uniform logs—no binders, no chemicals. Our proprietary furnaces precisely control oxygen, temperature, and time, ensuring every log is dense, carbon-rich, and burns consistently.",
        "Think of it like sous vide—each piece is identical, delivering predictable results.",
        "Higher heat = fewer LBs needed. Longer burn time = less frequent refills. More control = better performance.",
      ],
    },
  ],
  woodCompare: {
    title: "And about that wood..",
    without: [
      "Purchase a cord (a volume unit) but you don’t know how much you are getting.",
      "Different sizes.",
      "Humidity varies and can contain high moisture.",
      "Messy storage, dirt, mold, and bulk purchase only.",
      "Uneven heat (BTU), inconsistent burn time.",
    ],
    withTitle: "With Prime 6",
    with: [
      "Same size, clean and in a stackable box.",
      "Less than 5% moister.",
      "Sold by the LB so measurable food cost.",
      "Same BTU, same burn time.",
      "Easy training.",
      "Order a case or a pallet, no bulk commitment.",
    ],
  },
  costList: [
    "Burns hotter, lasts longer – fewer refills per service",
    "40-60% less wood needed",
    "60% reduction in charcoal use",
    "1LB of Prime 6 = 3LBs of regular charcoal",
    "Sold by the LB, not the cord – full cost transparency",
    "30% fewer hood cleanings",
    "Uniform shape, weight, and density",
    "easy to train staff & control costs",
    "No moisture, no sparks, <5% ash",
    "100% hardwood – no chemicals, no additives",
  ],
  about: {
    kicker: "Who we are",
    quote:
      "You never change things by fighting the existing reality. To change something, build a new model that makes the existing model obsolete.",
    quoteBy: "R. Buckminster Fuller",
    title: "Igniting environmental change",
    paragraphs: [
      "We upcycle wood waste to reduce tree-cutting and waste in hospitality. Our USDA-certified products are made with proprietary, emissions-free methods.",
      "As a woman-owned U.S. business, we’re building a local facility to support domestic mills and forest health through a USDA partnership.",
      "Plus, we plant one tree per case sold with Veritree, a global leader in reforestation.",
    ],
    partnership: "Our Partnership with",
    impactTitle: "Our Impact",
    impact: [
      "At Prime 6, sustainability is integral to our mission. Through our partnership with veritree, we're enhancing our environmental commitment by restoring vital ecosystems and supporting global reforestation efforts. The trees we've planted are contributing to carbon sequestration, biodiversity enhancement, and community development.",
    ],
    visit: "Visit Impact Hub",
    sections: [
      {
        id: "senegal",
        title: "Agroforestry in Senegal, Africa",
        paragraphs: [
          "A significant portion of our efforts focuses on agroforestry—a sustainable land-use approach that integrates trees with crops and livestock. This method not only restores degraded lands but also improves soil health, water quality, and crop yields, offering economic benefits to local farmers.",
          "The Senegal program seeks to restore as much of the 30,000 hectares of degraded land surrounding the forests as possible, starting with 6,000 farming families each with one hectare each.",
          "By rehabilitating degraded lands, implementing sustainable practices, and fostering community ownership, the program aims to contribute to the long-term richness and sustainability of the Gambia River Watershed.",
        ],
      },
      {
        id: "social",
        title: "Social and Environmental Impact",
        paragraphs: [
          "Our reforestation projects extend beyond environmental restoration; they foster significant social and economic benefits:",
        ],
        list: [
          "Employment Creation: By involving local communities in tree planting and maintenance, we've generated employment opportunities, contributing to economic stability.",
          "Food Security: Agroforestry practices have led to a 706% increase in access to nutrition, reducing severe food insecurity among farm families from 56% to 8%.",
          "Carbon Sequestration: Our planted trees are projected to sequester significant amounts of CO₂ over their lifetimes, aiding in climate change mitigation efforts.",
        ],
      },
      {
        id: "oregon",
        title: "Oregon, US Wildfire Restoration",
        paragraphs: [
          "A groundbreaking reforestation effort is now underway to restore the region’s tree canopy and enhance water quality.",
          "This transformative project will revitalize ecosystems, safeguard biodiversity, and ensure a sustainable future for wildlife and communities alike, contributing to long-term climate resilience.",
        ],
      },
    ],
    close:
      "Through these initiatives, Prime 6 is dedicated to creating a regenerative future where business growth aligns with environmental stewardship and community well-being.",
    save: "Save Money. Go Green. Be Efficient.",
  },
  grillers: {
    kicker: "For the home griller",
    title: "Fuel for the Fire Masters",
    paragraphs: [
      "For the home pitmaster who treats every cook like a craft, Prime 6 delivers the performance you need to grill and smoke like a pro.",
      "Made from hardwood and compressed into ultra-dense hex logs, Prime 6 burns hotter, longer, and cleaner than traditional lump or briquettes—giving you precise temperature control and fewer reloads.",
      "It’s the fuel of choice for serious backyard BBQ enthusiasts who care about quality, performance, and sustainability.",
    ],
    masters: "Prime 6 is built for serious home cooks",
    mastersBody: [
      "Prime 6 is built for serious home cooks—those who grill, smoke, and bake with precision. Whether you're firing up a smoker, a Kamado-style grill, or a pizza oven, Prime 6 outperforms any fuel on the market.",
      "It burns hotter, cleaner, and longer—lasting over 14 hours in a smoker with steady, reliable heat. Its dense design means a little goes a VERY long way, especially in Kamado grills where efficiency is everything. This isn’t your grandfather’s charcoal—it’s smarter, stronger, and engineered for next-level BBQ.",
    ],
    products: [
      {
        title: "Charcoal",
        blurb: "For the grill, smoker and pizza oven",
        body: [
          "Professional Grade Charcoal",
          "Burns hotter, longer, and cleaner—perfect for smokers, grills, and pizza ovens.",
          "Made from wood with zero fillers or chemicals. A little goes a long way.",
        ],
        image: "/media/charcoal-case.png",
        alt: "22LB no background.png",
        orderLabel: "ORDER FROM",
        retailers: [
          {
            name: "Walmart",
            href: "https://www.walmart.com/ip/Prime-6-Long-Burning-Charcoal-22lbs-1lb-Prime-6-3lb-lump/899013576",
          },
          {
            name: "Lowe's",
            href: "https://www.lowes.com/pd/Prime-6-Prime-6-Pro-Pack-22lb/1003093538",
          },
          {
            name: "Target",
            href: "https://www.target.com/p/prime-6-pro-pack-22lbs-charcoal/-/A-90414210",
          },
        ],
      },
      {
        title: "Firelogs",
        blurb: "For you fire pit, place or Pizza oven",
        body: [
          "High Performing Firelogs",
          "Clean-burning, long-lasting firelogs from upcycled hardwood.",
          "Perfect for fireplaces, fire pits, wood stoves, and outdoor gatherings. No additives, no mess.",
        ],
        image: "/media/firelogs.png",
        alt: "Prime 6_Firelogs 22lb case.png",
        orderLabel: "ORDER FROM",
        retailers: [
          {
            name: "Lowe's",
            href: "https://www.lowes.com/pd/Prime-6-Sustainable-Fire-Logs-9CT/5005371897",
          },
        ],
      },
      {
        title: "Grill Kit",
        blurb: 'Everything you need in a "all in one" on the go solution',
        body: [
          "Using your Prime 6 Grilling Kit",
          "All-In-One is All you need",
          "Our Grilling Kit has everything you need to get cooking—whether you're camping, tailgating, or just firing up the grill in your backyard. No mess, no hassle—just a perfect flame, every time.",
          "The portable, easy-to-use chimney starter comes pre-packed with Prime 6 Charcoal and includes two powerful fire starters, so you’re ready to go straight out of the box.",
          "Simply place the fire starters under the chimney, light them up, and let the charcoal do the rest. Once it’s glowing hot, carefully pour it into your grill or fire pit, and you're ready to cook.",
          "Light. Pour. Grill. No messy bags, no chemicals, no stress—just effortless grilling with clean, consistent heat for the perfect sear. Take it anywhere, fire it up, and enjoy a better grilling experience.",
          "For the great outdoor. Don't limit yourself.",
        ],
        image: "/media/grill-kit.png",
        alt: "Grilling_Kit_no background.png",
        orderLabel: "ORDER FROM",
        retailers: [
          {
            name: "Target",
            href: "https://www.target.com/p/prime-6-grilling-kit-7lbs-charcoal/-/A-90414212",
          },
        ],
      },
    ],
  },
  pro: {
    kicker: "Pro Chefs",
    title: "Proudly powering live fire everywhere",
    intro:
      "Wood is flavorful and we love seeing the flames. But wood is also draining your budget, its unreliable and inconsistent. Using Prime 6 in combination with wood will supplement the embers and give you a better, longer and consistent heat source without impacting your flavor profile.",
    frameTitle: "The Frame Method",
    frame: [
      "Mixing in Prime 6 with your embers will reduce your dependency on wood.",
      'But for optimal results, try creating a wood "frame" and placing the charcoal in the center. The intense heat from the charcoal will slowly smoke up the wood - creating the same flavor profile without going through mountains of wood.',
      "Use Prime 6 as your utility.",
    ],
    embersTitle: "Embers",
    embers: [
      "Embers require constant wood feeding into your grill. They produce low temps for very little time. Prime 6 can supplement your embers and cut down the amount of wood you are using.",
      "In addition, you no longer have to deal with wood management, inconsistent dealers, checking for mold, moisture and poor quality wood.",
    ],
    closer: "Closer Look",
    pizzaTitle: "Pizza",
    pizza: [
      "Both our charcoal and our logs can reduce the operational costs of operating your pizza oven.",
      "Depending on the charcoal to wood ratio, starting with charcoal to bring your oven to temp and maintain that temperature, will cut down your wood usage.",
      "Adding the logs creates flame and fire and that additional heat that is perfect for your pizza.",
      "This power combo provides steady heat for hours, while eliminating the chance of ever throwing a wet piece of wood in the oven.",
      "Taking a closer look, the bottom part of the heat source, previously made up from the embers of the initial wood burnt down, is now just Prime 6 Charcoal.",
      "This baseline of heat will maintain a steady temperature in the oven throughout service. On top, there are firelogs for flame.",
      "Using this combination can reduce the amount of wood needed for service since chef is not dependent only on the heat that would come from burning wood.",
      "Some Pizza operators manage to use the charcoal base, while needing to add one log or even a half a log to keep the fire going. By doing so they eliminate their dependency on inconsistent wood, free up storage space and most importantly - take control of their food cost.",
    ],
    anywhere: "Anywhere there is fire",
  },
  sampleForm: {
    kicker: "Get a Sample",
    title: "Get a FREE Sample",
    steps: ["Qualify", "Details"],
    nextTitle: "What happens next",
    next: [
      "Samples available only for professionals in the hospitality or procurement industry.",
      "Foodservice and Hospitality businesses can receive a free sample of Prime 6 to try out.",
      "Fill out the form and we will send you a sample.",
    ],
    eligibleQ: "Are you in hospitality or procurement?",
    eligibleYes: "Yes — hospitality or procurement professional",
    eligibleNo: "No — this sample is not for me",
    blocked: "Samples available only for professionals in the hospitality or procurement industry.",
    equipment: "Application / Equipment",
    equipmentOptions: [
      "Wood burning grill",
      "Grillworks/J&R/Grills by Demant",
      "Pizza Oven",
      "Charcoal oven (MiBrassa/Josper/Kopa)",
      "Hibachi/Yakitori",
      "Hearth",
      "Tandoor",
      "Other",
    ],
    fuelsQ: "What fuels do you currently use?",
    fuels: ["Charcoal", "Wood", "Both"],
    samplesQ: "Which samples do you need?",
    samples: ["Charcoal", "Wood", "Both"],
    continue: "Continue",
    back: "Back",
    first: "First name",
    last: "Last name",
    email: "Email",
    phone: "Phone",
    restaurant: "Restaurant Name",
    url: "Business URL (website, etc.)",
    address: "Shipping / Restaurant Address",
    distributors: "Preferred Distributors (provide 3 options)",
    distributorPlaceholders: ["i.e. Sysco, US Foods", "i.e. Halperns, Baldor", "i.e. D'Artagnan, Fortune Fish"],
    submit: "Submit",
    thanks: "Thanks for submitting!",
    required: "Required",
  },
  terry: {
    kicker: "View the full interview",
    title: "Chef Terry Koval",
    lead: "Listen to James Beard award winner Chef Terry Koval talk about playing with fire and why Prime 6 is his fuel of choice.",
    paragraphs: [
      "Chef Terry Koval is the owner and chef at The Deer and The Dove and B-SIDE in Decatur, GA, which he opened with his wife Jenn in June 2019. These restaurants were highly anticipated, earning accolades from Food and Wine magazine and Eater Atlanta. Koval has been recognized with numerous awards, including the Georgia Organics Farmer Champion gold from 2021 to present, the Slow Food Snail of Approval award, and the James Beard Best Chef Southeast in 2023. He is also recommended by the Michelin Guide.",
      "Before opening his own restaurants, Koval moved to Atlanta in 2000, starting at Buckhead Diner and then Canoe, where he became Executive Sous Chef. He later worked at Lobby at TWELVE and Room at TWELVE, the latter receiving 3 stars from The Atlanta Journal-Constitution under his leadership. In 2010, he conceptualized Farm Burger, which gained national recognition. He then became Executive Chef at Wrecking Bar Brewpub in 2013, earning 3 out of 4 stars from The Atlanta Journal-Constitution and several awards. Koval has also appeared on Food Network's \"Diners, Drive-Ins, and Dives\" and \"Chopped.\"",
      "Koval is an active supporter of local food organizations such as Georgia Organics and Slow Food Atlanta, and he resides in Decatur, GA, with his family.",
    ],
  },
  news: {
    kicker: "ABC's Shark Tank",
    title: "See Prime 6 on Shark Tank",
    lead: "See how Prime 6 founders closed the deal with Shark Kevin O'Leary on season 12 episode 6",
    videos: [
      { title: "Shark Tank Update 2025", time: "02:52" },
      { title: "Shark Tank Short", time: "02:07" },
      { title: "Prime 6 on Shark Tank", time: "10:20" },
      { title: "Shark Tank Update 2021", time: "02:05" },
    ],
    source: "In The News",
  },
  sustain: {
    kicker: "Veritree",
    title: "Sustainability Dashboard",
    prompt: "Enter number of cases used to calculate your positive impact",
    disclaimer:
      "The metrics and statistics presented on this page are based on average calculations derived from publicly available scientific data and research. These figures are intended solely for informational purposes to provide a general understanding of potential environmental impacts. The values displayed are approximate and may not accurately represent specific or localized conditions. Prime 6 does not guarantee the accuracy, reliability, or completeness of the data and disclaims any liability for decisions made based on this information.",
    hub: "Visit Impact Hub",
    live: "Sustainability Dashboard",
  },
  contact: {
    kicker: "Contact Us",
    title: "Contact Us",
    lead: "Any questions about Prime 6 products? Leave us a message and we will get back to you.",
    first: "First Name",
    last: "Last Name",
    email: "Email",
    message: "Message",
    send: "Send",
    thanks: "Thanks for submitting!",
    company: "Heatman Charcoal LLC",
    address: ["24 Phillips Lane", "Fairmont, WV 26554"],
    phoneLabel: "Phone",
    phone: "9296761083",
  },
};
