import type { Copy } from "./types";

export const pt: Copy = {
  meta: {
    homeTitle: "Início | Prime 6 Carvão e lenha de alto desempenho",
    homeDescription:
      "A Prime 6 tem orgulho de alimentar alguns dos melhores restaurantes do país. De fornos Josper e MiBrassa a grelhas abertas a lenha, reduzimos custos, aumentamos a eficiência e ajudamos a hotelaria a ter um impacto positivo no ambiente.",
    whyTitle: "Por que a Prime 6 | Prime 6",
    whyDescription:
      "Saiba como os nossos produtos podem reduzir os custos de uma cozinha de fogo vivo e aumentar a eficiência da equipa. Poupe dinheiro, trabalhe melhor e faça o bem.",
    aboutTitle: "Sobre | Prime 6",
    aboutDescription:
      "A Prime 6 tem orgulho de alimentar alguns dos melhores restaurantes do país. De fornos Josper e MiBrassa a grelhas abertas a lenha, reduzimos custos, aumentamos a eficiência e ajudamos a hotelaria a ter um impacto positivo no ambiente.",
    grillersTitle: "Churrasqueiros | Prime 6",
    chefsTitle: "Chefs profissionais | Prime 6",
    chefsDescription:
      "Onde houver fogo. Do Josper ou MiBrassa aos fornos de pizza e grelhas a lenha. A Prime 6 funciona onde quer que a comida seja cozinhada na chama.",
    sampleTitle: "Pedir uma amostra | Prime 6",
    sampleDescription:
      "Empresas de foodservice e hotelaria podem receber uma amostra grátis da Prime 6 para experimentar. Preencha o formulário e enviaremos uma amostra.",
    terryTitle: "Terry Koval | Prime 6",
    newsTitle: "Nas notícias | Prime 6",
    newsDescription:
      "Veja como os fundadores da Prime 6 fecharam o acordo com o Shark Kevin O'Leary na temporada 12, episódio 6",
    sustainTitle: "Painel de sustentabilidade | Prime 6",
    contactTitle: "Contacto | Prime 6",
    contactDescription:
      "Dúvidas sobre os produtos Prime 6? Deixe uma mensagem e entraremos em contacto.",
  },
  chrome: {
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    language: "Idioma",
    theme: "Tema",
    light: "Claro",
    dark: "Escuro",
    sampleCta: "Pedir uma amostra para hotelaria",
    builtBy: "Built by dglxss",
    stayInTouch: "Fique em contacto",
    subscribe: "Subscrever",
    subscribeThanks: "Obrigado! Manteremos o contacto",
    emailPlaceholder: "adicione o seu email aqui",
    join: "Quer juntar-se à equipa?",
    apply: "CANDIDATAR",
    footerNote: "PRIME 6",
  },
  nav: {
    home: "Início",
    grillers: "Churrasqueiros",
    why: "Por que a Prime 6",
    chefs: "Chefs profissionais",
    about: "Sobre",
    biochar: "Biochar",
    sample: "Pedir amostra",
    news: "Shark Tank e notícias",
    sustainability: "Painel de sustentabilidade",
    contact: "Contacte-nos",
  },
  hero: {
    tagline: ["Mais calor", "menos desperdício", "mais poupança"],
    cta: "Pedir uma amostra para hotelaria",
    description: "Carvão e lenha de alto desempenho",
    heading: ["Testado", "Fogo", "Aperfeiçoado"],
    stats: [
      { value: "60", unit: "%", kicker: "Até", label: "Custos de\ncombustível" },
      { value: "22", unit: "LB", label: "Tudo utilizável\nsem desperdício" },
      { value: "1", unit: "", label: "Árvore por caixa\ncom a Veritree" },
    ],
  },
  proof: [
    { label: "USDA Certified", detail: "Produtos certificados USDA", href: "/about#usda" },
    { label: "Empresa de mulher", detail: "Empresa dos EUA detida por uma mulher", href: "/about" },
    { label: "Avendra", detail: "Avendra approved", href: "/#avendra" },
    { label: "Shark Tank", detail: "Temporada 12 episódio 6 · Kevin O'Leary", href: "/shark-tank" },
    { label: "Veritree", detail: "Uma árvore por caixa", href: "https://impact.veritree.com/prime6", external: true },
    {
      label: "Chef Terry Koval",
      detail: "James Beard Award Winner Best Chef South East",
      href: "/terry-koval",
    },
    { label: "Chef Grant Achatz", detail: "Alinea", href: "/#chefs" },
  ],
  burn: {
    kicker: "A diferença Prime 6",
    title: "Densidade. Processo. Resultados.",
    beats: [
      {
        label: "01",
        title: "Densidade",
        body: [
          "Tudo começa na matéria-prima.",
          "Reciclamos resíduos de madeira para reduzir o corte de árvores e o desperdício na hotelaria.",
          "Em vez de madeira aleatória com densidade imprevisível, comprimimos serradura em toros ultra-densos — sem químicos, sem colas, sem aditivos. Um só ingrediente: hardwood.",
          "3 vezes mais denso que a madeira, sem bolsas de ar nem humidade, com a consistência necessária para alto desempenho.",
        ],
        image: "/media/bark.jpg",
        alt: "Casca de árvore",
      },
      {
        label: "02",
        title: "Processo",
        body: [
          "A precisão importa.",
          "A Prime 6 usa fornos avançados para controlar tempo, temperatura e níveis de oxigénio, num processo preciso com matéria-prima uniforme. Isso maximiza a eficiência e alcança o maior teor de carbono sem sacrificar a densidade. Mais carbono = melhor desempenho.",
          "Cada peça de carvão P6 tem a mesma alta qualidade — sem pedrinhas inúteis, sem pedaços pouco carbonizados. Só combustível puro e consistente.",
        ],
        image: "/media/charcoal.jpg",
        alt: "Carvão Prime 6",
      },
      {
        label: "03",
        title: "Resultados",
        body: [
          "A alimentar fogo vivo em todo o lado.",
          "A Prime 6 tem orgulho de alimentar alguns dos melhores restaurantes do país. De fornos Josper e MiBrassa a grelhas abertas a lenha, reduzimos custos, aumentamos a eficiência e ajudamos a hotelaria a ter um impacto positivo no ambiente.",
          "Fiabilidade em cada toro. Carvão ou lenha, a Prime 6 entrega o mesmo desempenho — sempre.",
        ],
        image: "/media/pizza.jpg",
        alt: "Pormenor de pizza",
      },
    ],
  },
  whyHome: {
    kicker: "Por que a Prime 6?",
    title: "Engenhado para performar",
    lead: "Mais calor, menos desperdício, mais poupança.",
    body: [
      "A Prime 6 queima mais quente, dura mais e corta custos de combustível em até 60%.",
      "Engenhado para eficiência, o nosso carvão entrega desempenho consistente sem desperdício — só hardwood de alto carbono. Menos reabastecimento, custos previsíveis e melhores resultados.",
    ],
    mission:
      "Somos uma empresa com missão, detida por uma mulher, USDA Certified e parceira da maior organização de reflorestação do mundo.",
    link: "Veja por que os chefs escolhem a Prime 6",
  },
  audiences: {
    kicker: "Para quem somos?",
    title: "Para quem somos?",
    hospitality: "Profissionais de hotelaria",
    hospitalityBody:
      "De fornos Josper e MiBrassa a grelhas abertas a lenha, reduzimos custos, aumentamos a eficiência e ajudamos a hotelaria a ter um impacto positivo no ambiente.",
    pit: "Pit masters e churrasqueiros profissionais",
    pitBody:
      "Para o pitmaster caseiro que trata cada cozedura como um ofício, a Prime 6 entrega o desempenho para grelhar e fumar como um profissional.",
  },
  economics: {
    id: "calculator",
    kicker: "Gaste menos. Trabalhe melhor. Lucre mais.",
    title: "Como é que a Prime 6 reduz custos?",
    fuelQuestion: "Que combustíveis usa hoje?",
    fuels: ["Carvão", "Lenha", "Ambos"],
    weekly: "LB semanais",
    weeklyHint: "Operações com carvão veem uma queda significativa nas LB compradas por semana.",
    hours: "Horas numa carga atual",
    hoursHint: "O seu número. O tempo de queima da Prime 6 abaixo é o desempenho publicado, não um multiplicador.",
    refills: "Reabastecimentos por serviço",
    refillsHint: "Queima mais quente, dura mais — menos reabastecimentos por serviço.",
    ceiling: "Teto publicado",
    ceilingHint: "Corta custos de combustível em até 60%. O controlo para nesse teto.",
    estimate: "Está a pagar por quilos ou por desempenho?",
    estimateBody:
      "Usa significativamente menos quilos de combustível sólido, por isso, mesmo com um custo por quilo um pouco mais alto, a poupança mensal total é substancial. Os números abaixo são unidades relativas no teto que definir.",
    traditional: "Combustível atual",
    traditionalSub: "Quilos, horas e reabastecimentos que introduziu",
    ceilingCard: "Até 60%",
    ceilingSub: "Teto publicado. Sem estimativa em dólares.",
    withPrime: "Com a Prime 6",
    withSub: "Unidades relativas dentro do teto publicado",
    lbs: "LB / semana",
    refillsUnit: "Reabastecimentos",
    hoursUnit: "Horas que introduziu",
    equivalence: "1 LB de Prime 6 = 3 LB de carvão comum",
    woodNote:
      "Com lenha, o impacto é ainda maior — muitos cortam o uso de lenha em 40-60%, alguns até 80%, ao complementar as brasas com P6. Esta calculadora não ultrapassa o teto publicado de “até 60%”.",
    burnPublished: "A Prime 6 fornece calor estável e consistente durante 5+ horas, com pouca cinza e uma queima limpa.",
    smokerPublished: "Mais de 14 horas num smoker, com calor estável e fiável.",
    disclaimer: [
      "A Prime 6 queima mais quente, dura mais e corta custos de combustível em até 60%.",
      "Os valores apresentados são aproximados e podem não representar com precisão condições específicas ou locais. A Prime 6 não garante a exatidão, fiabilidade ou integridade dos dados e declina responsabilidade por decisões tomadas com base nesta informação.",
    ],
    noDollars: "Vendido à LB, não à corda — transparência total de custo. Só unidades relativas.",
  },
  chefsBlock: {
    kicker: "Em poucas palavras",
    title: "O que os profissionais dizem",
    terryName: "Chef Terry Koval",
    terryAward: "James Beard Award Winner",
    terryRole: "Chef e proprietário — Dear and the Dove",
    terryBody:
      "Ouça o Chef Terry Koval, James Beard Award Winner Best Chef South East, explicar de forma simples e direta por que a lareira dele corre com carvão Prime 6.",
    interview: "Ver a entrevista completa",
    pros: "O que os profissionais dizem",
    chefs: [
      { name: "Chef Grant Achatz, Alinea", image: "/media/grant.jpg", alt: "Chef Grant Achatz, Alinea" },
      { name: "Chef John Um, Sushi Samba", image: "/media/john-um.jpg", alt: "Chef John Um, Sushi Samba" },
      { name: "Chef John Tesar, Knife", image: "/media/john-tesar.jpg", alt: "Chef John Tesar, Knife" },
      {
        name: "Chef Gary Francis Xavier LaMorte, Honest",
        image: "/media/gary.jpg",
        alt: "Chef Gary Francis Xavier LaMorte, Honest",
      },
      {
        name: "Chef Brian Howard, proprietário do Sparrow + WOLF",
        image: "/media/brian.jpg",
        alt: "Chef Brian Howard, Owner of Sparrow + WOLF",
      },
      {
        name: "Chef celebridade Michael Simon",
        image: "/media/simon.jpg",
        alt: "Celebrity Chef Michael Simon",
      },
      {
        name: "Chef Hugh Mangum, sócio @Mighty Quinn's BBQ",
        image: "/media/hugh.jpg",
        alt: "Chef Hugh Mangum, Partner @Mighty Quinn's BBQ",
      },
      {
        name: "Gentle Giant Brewing Company",
        image: "/media/gentle.jpg",
        alt: "Gentle Giant Brewing Company",
      },
    ],
  },
  sampleBand: {
    title: "Amostra GRÁTIS",
    body: "Amostras disponíveis apenas para profissionais da hotelaria ou de compras.",
    cta: "PEDIR AMOSTRA",
  },
  whyClose: {
    title: "Eficiente. Previsível. Poupa custo.",
    bottom:
      "Conclusão. Usa significativamente menos quilos de combustível sólido, por isso, mesmo com um custo por quilo um pouco mais alto, a poupança mensal total é substancial.",
  },
  whyPage: [
    {
      id: "transparency",
      title: "Transparência e consistência",
      paragraphs: [
        "No fim do dia, trata-se de reduzir custo.",
        "O nosso carvão denso e rico em carbono queima mais quente e por mais tempo, reduzindo a quantidade necessária. Operações com carvão veem uma queda significativa nas LB compradas por semana.",
        "Com lenha, o impacto é ainda maior — muitos cortam o uso de lenha em 40-60%, alguns até 80%, ao complementar as brasas com P6. Vendido à LB, não à corda, o P6 dá transparência total de custo.",
        "Algumas cozinhas de pizza têm isto numa ciência, adicionando 1 toro a cada XX minutos para manter o forno à temperatura. Isso garante controlo de custo e simplifica a formação.",
        "Custos de combustível previsíveis — independentemente de quem está na linha.",
      ],
    },
    {
      id: "pebbles",
      title: "Está a pagar por ar e pedrinhas?",
      paragraphs: [
        "O carvão lump tradicional traz desperdício incluído.",
        "Quando compra ao peso, paga por tudo — pedaços grandes, pedaços pequenos e pó.",
        "Qualquer coisa abaixo de 1,5 polegadas não acrescenta calor nem duração reais, e muitas vezes queima antes de a grelha ou o forno estar pronto.",
        "O desperdício pode ir de 5% a 35%, o que significa que quanto mais pedaços pequenos no saco, mais paga por cada quilo utilizável.",
        "Se metade do saco é pó, está a pagar o dobro.",
        "Com a Prime 6, usa as 22 LB inteiras — sem pó, sem pedrinhas, sem desperdício. Só carvão puro.",
      ],
    },
    {
      id: "value",
      title: "Valor. Desempenho. Eficiência.",
      paragraphs: [
        "Alto desempenho não deve custar um preço alto.",
        "Mais calor, menos combustível, custos mais baixos.",
        "O nosso calor alto e a longa queima significam que usa menos lenha ou carvão por serviço.",
        "Não estamos aqui para substituir a sua lenha — estamos aqui para complementar as brasas.",
        "A Prime 6 fornece calor estável e consistente durante 5+ horas, com pouca cinza e uma queima limpa, poupando dinheiro em cada passo.",
      ],
    },
    {
      id: "density",
      title: "Densidade",
      paragraphs: [
        "Tudo começa na matéria-prima.",
        "Em vez de madeira aleatória com densidade imprevisível, comprimimos serradura em toros ultra-densos — sem químicos, sem colas, sem aditivos.",
        "Um só ingrediente: hardwood.",
        "3 vezes mais denso que a madeira, sem bolsas de ar nem humidade, com a consistência necessária para alto desempenho.",
      ],
    },
    {
      id: "process",
      title: "Processo",
      paragraphs: [
        "A precisão importa.",
        "A produção tradicional de carvão é imprevisível — tamanhos e densidades diferentes levam a resultados inconsistentes.",
        "A Prime 6 usa fornos avançados para controlar tempo, temperatura e níveis de oxigénio, num processo preciso com matéria-prima uniforme. Isso maximiza a eficiência e alcança o maior teor de carbono sem sacrificar a densidade. Mais carbono = melhor desempenho.",
        "Cada peça de carvão P6 tem a mesma alta qualidade — sem pedrinhas inúteis, sem pedaços pouco carbonizados. Só combustível puro e consistente.",
      ],
    },
    {
      id: "results",
      title: "Resultados",
      paragraphs: [
        "Fiabilidade em cada toro.",
        "Carvão ou lenha, a Prime 6 entrega o mesmo desempenho — sempre.",
        "Quando afina o setup, o P6 queima de forma previsível. Num forno de pizza, um toro a cada X minutos mantém o calor estável todos os dias.",
        "Numa grelha, Mibrasa, lareira ou qualquer equipamento, dá resultados consistentes. Sem gestão de fogo, sem reabastecimento constante, sem adivinhação.",
        "Só consistência em que pode confiar.",
      ],
    },
    {
      id: "pounds",
      title: "Está a pagar por quilos ou por desempenho?",
      paragraphs: [
        "A qualidade do carvão resume-se a duas coisas: matéria-prima e carbonização.",
        "Com carvão lump, não controla a espécie, a densidade nem o tamanho — o processo aplica o mesmo calor a peças desiguais, como assar um prime rib e um filet juntos. Um fica passado, o outro cru.",
        "Na Prime 6, engenhamos o carvão. Extrudimos serradura em toros uniformes — sem ligantes, sem químicos. Os nossos fornos proprietários controlam oxigénio, temperatura e tempo, para que cada toro seja denso, rico em carbono e queime de forma consistente.",
        "Pense em sous vide — cada peça é idêntica e o resultado é previsível.",
        "Mais calor = menos LB necessárias. Mais tempo de queima = reabastecimentos menos frequentes. Mais controlo = melhor desempenho.",
      ],
    },
  ],
  woodCompare: {
    title: "E aquela lenha..",
    without: [
      "Compra uma corda (unidade de volume) mas não sabe quanto está a receber.",
      "Tamanhos diferentes.",
      "A humidade varia e pode ser alta.",
      "Armazenamento sujo, terra, bolor, e só compra a granel.",
      "Calor irregular (BTU), tempo de queima inconsistente.",
    ],
    withTitle: "Com a Prime 6",
    with: [
      "O mesmo tamanho, limpo e numa caixa empilhável.",
      "Menos de 5% de humidade.",
      "Vendido à LB, para um food cost mensurável.",
      "O mesmo BTU, o mesmo tempo de queima.",
      "Formação fácil.",
      "Encomende uma caixa ou uma palete, sem compromisso de granel.",
    ],
  },
  costList: [
    "Queima mais quente, dura mais — menos reabastecimentos por serviço",
    "40-60% menos lenha necessária",
    "60% de redução no uso de carvão",
    "1 LB de Prime 6 = 3 LB de carvão comum",
    "Vendido à LB, não à corda — transparência total de custo",
    "30% menos limpezas de exaustão",
    "Forma, peso e densidade uniformes",
    "fácil de formar a equipa e controlar custos",
    "Sem humidade, sem faíscas, <5% de cinza",
    "100% hardwood — sem químicos, sem aditivos",
  ],
  about: {
    kicker: "Quem somos",
    quote:
      "Nunca se muda as coisas lutando contra a realidade existente. Para mudar algo, construa um novo modelo que torne o modelo existente obsoleto.",
    quoteBy: "R. Buckminster Fuller",
    title: "A acender mudança ambiental",
    paragraphs: [
      "Reciclamos resíduos de madeira para reduzir o corte de árvores e o desperdício na hotelaria. Os nossos produtos certificados USDA são feitos com métodos proprietários e sem emissões.",
      "Como empresa dos EUA detida por uma mulher, estamos a construir uma instalação local para apoiar serrações nacionais e a saúde da floresta através de uma parceria USDA.",
      "Além disso, plantamos uma árvore por caixa vendida com a Veritree, líder global em reflorestação.",
    ],
    partnership: "A nossa parceria com",
    impactTitle: "O nosso impacto",
    impact: [
      "Na Prime 6, a sustentabilidade é parte da missão. Através da parceria com a veritree, reforçamos o compromisso ambiental ao restaurar ecossistemas e apoiar a reflorestação global. As árvores que plantámos contribuem para sequestro de carbono, biodiversidade e desenvolvimento comunitário.",
    ],
    visit: "Visitar o Impact Hub",
    sections: [
      {
        id: "senegal",
        title: "Agrofloresta no Senegal, África",
        paragraphs: [
          "Uma parte significativa do esforço foca-se na agrofloresta — um uso da terra que integra árvores com culturas e gado. Este método restaura terras degradadas e melhora o solo, a água e as colheitas, com benefício económico para agricultores locais.",
          "O programa no Senegal procura restaurar o máximo possível dos 30.000 hectares de terra degradada em redor das florestas, começando com 6.000 famílias agrícolas, cada uma com um hectare.",
          "Ao reabilitar terras degradadas, aplicar práticas sustentáveis e fomentar a propriedade comunitária, o programa quer contribuir para a riqueza e sustentabilidade de longo prazo da bacia do rio Gâmbia.",
        ],
      },
      {
        id: "social",
        title: "Impacto social e ambiental",
        paragraphs: [
          "Os projetos de reflorestação vão além da restauração ambiental; geram benefícios sociais e económicos significativos:",
        ],
        list: [
          "Criação de emprego: Ao envolver comunidades locais na plantação e manutenção, gerámos oportunidades de emprego e estabilidade económica.",
          "Segurança alimentar: Práticas agroflorestais levaram a um aumento de 706% no acesso a nutrição, reduzindo a insegurança alimentar grave nas famílias agrícolas de 56% para 8%.",
          "Sequestro de carbono: As árvores plantadas deverão sequestrar quantidades significativas de CO₂ ao longo da vida, ajudando a mitigar as alterações climáticas.",
        ],
      },
      {
        id: "oregon",
        title: "Restauro pós-incêndio no Oregon, EUA",
        paragraphs: [
          "Um esforço de reflorestação está em curso para restaurar a copa da região e melhorar a qualidade da água.",
          "Este projeto vai revitalizar ecossistemas, proteger a biodiversidade e assegurar um futuro sustentável para a vida selvagem e as comunidades, contribuindo para resiliência climática de longo prazo.",
        ],
      },
    ],
    close:
      "Com estas iniciativas, a Prime 6 dedica-se a um futuro regenerativo em que o crescimento do negócio alinha com a gestão ambiental e o bem-estar da comunidade.",
    save: "Poupe dinheiro. Seja verde. Seja eficiente.",
  },
  grillers: {
    kicker: "Para quem grelha em casa",
    title: "Combustível para os mestres do fogo",
    paragraphs: [
      "Para o pitmaster caseiro que trata cada cozedura como um ofício, a Prime 6 entrega o desempenho para grelhar e fumar como um profissional.",
      "Feita de hardwood e comprimida em toros hexagonais ultra-densos, a Prime 6 queima mais quente, por mais tempo e mais limpa do que lump ou briquetes tradicionais — com controlo de temperatura e menos recargas.",
      "É o combustível de quem leva o BBQ de quintal a sério e se importa com qualidade, desempenho e sustentabilidade.",
    ],
    masters: "A Prime 6 é feita para cozinheiros caseiros sérios",
    mastersBody: [
      "A Prime 6 é feita para cozinheiros caseiros sérios — quem grelha, fuma e assa com precisão. Num smoker, numa grelha estilo Kamado ou num forno de pizza, a Prime 6 supera qualquer combustível do mercado.",
      "Queima mais quente, mais limpa e por mais tempo — mais de 14 horas num smoker com calor estável e fiável. O desenho denso faz com que pouco renda muito, especialmente em grelhas Kamado, onde a eficiência é tudo. Não é o carvão do seu avô — é mais inteligente, mais forte e engenhado para BBQ de outro nível.",
    ],
    products: [
      {
        title: "Carvão",
        blurb: "Para a grelha, o smoker e o forno de pizza",
        body: [
          "Carvão de grau profissional",
          "Queima mais quente, por mais tempo e mais limpo — perfeito para smokers, grelhas e fornos de pizza.",
          "Feito de madeira, sem enchimentos nem químicos. Um pouco rende muito.",
        ],
        image: "/media/charcoal-case.png",
        alt: "Caixa de 22 LB",
        orderLabel: "ENCOMENDAR EM",
        retailers: [
          {
            name: "Walmart",
            href: "https://www.walmart.com/ip/Prime-6-Long-Burning-Charcoal-22lbs-1lb-Prime-6-3lb-lump/899013576",
          },
          { name: "Lowe's", href: "https://www.lowes.com/pd/Prime-6-Prime-6-Pro-Pack-22lb/1003093538" },
          { name: "Target", href: "https://www.target.com/p/prime-6-pro-pack-22lbs-charcoal/-/A-90414210" },
        ],
      },
      {
        title: "Firelogs",
        blurb: "Para a lareira, o fire pit ou o forno de pizza",
        body: [
          "Firelogs de alto desempenho",
          "Firelogs de queima limpa e longa, feitos de hardwood reciclado.",
          "Perfeitos para lareiras, fire pits, salamandras e encontros ao ar livre. Sem aditivos, sem sujidade.",
        ],
        image: "/media/firelogs.png",
        alt: "Caixa de firelogs Prime 6 22 lb",
        orderLabel: "ENCOMENDAR EM",
        retailers: [{ name: "Lowe's", href: "https://www.lowes.com/pd/Prime-6-Sustainable-Fire-Logs-9CT/5005371897" }],
      },
      {
        title: "Grill Kit",
        blurb: "Tudo o que precisa numa solução tudo-em-um para levar",
        body: [
          "A usar o Prime 6 Grilling Kit",
          "Tudo-em-um é tudo o que precisa",
          "O Grilling Kit tem tudo para cozinhar — campismo, tailgate ou o quintal. Sem sujidade, sem complicação — uma chama certa, sempre.",
          "A chaminé portátil vem pré-carregada com carvão Prime 6 e inclui dois acendedores, pronta a sair da caixa.",
          "Coloque os acendedores debaixo da chaminé, acenda e deixe o carvão fazer o resto. Quando estiver a brilhar, verta com cuidado para a grelha ou o fire pit e cozinhe.",
          "Acenda. Verta. Grelhe. Sem sacos sujos, sem químicos, sem stress — grelhar fácil com calor limpo e consistente para o sear perfeito. Leve para qualquer lado.",
          "Para o ar livre. Não se limite.",
        ],
        image: "/media/grill-kit.png",
        alt: "Prime 6 Grilling Kit",
        orderLabel: "ENCOMENDAR EM",
        retailers: [{ name: "Target", href: "https://www.target.com/p/prime-6-grilling-kit-7lbs-charcoal/-/A-90414212" }],
      },
    ],
  },
  pro: {
    kicker: "Chefs profissionais",
    title: "A alimentar fogo vivo em todo o lado",
    intro:
      "A lenha tem sabor e gostamos de ver as chamas. Mas a lenha também esgota o orçamento, é pouco fiável e inconsistente. Usar a Prime 6 com lenha complementa as brasas e dá uma fonte de calor melhor, mais longa e consistente sem alterar o perfil de sabor.",
    frameTitle: "The Frame Method",
    frame: [
      "Misturar Prime 6 nas brasas reduz a dependência de lenha.",
      "Para o melhor resultado, crie uma “frame” de lenha e coloque o carvão no centro. O calor intenso do carvão defuma a lenha devagar — o mesmo perfil de sabor sem montanhas de lenha.",
      "Use a Prime 6 como utilitário.",
    ],
    embersTitle: "Brasas",
    embers: [
      "As brasas exigem lenha constante na grelha. Produzem temperaturas baixas por muito pouco tempo. A Prime 6 pode complementar as brasas e reduzir a lenha que usa.",
      "Além disso, deixa de lidar com gestão de lenha, fornecedores inconsistentes, bolor, humidade e madeira de má qualidade.",
    ],
    closer: "Olhar mais de perto",
    pizzaTitle: "Pizza",
    pizza: [
      "Tanto o carvão como os toros podem reduzir o custo operacional do forno de pizza.",
      "Consoante a proporção carvão/lenha, começar com carvão para levar o forno à temperatura e mantê-la reduz o uso de lenha.",
      "Adicionar os toros cria chama e o calor extra perfeito para a pizza.",
      "Esta combinação dá calor estável durante horas e elimina o risco de atirar um pedaço de lenha húmida para o forno.",
      "Olhando de perto, a base da fonte de calor, antes feita das brasas da lenha inicial, passa a ser só carvão Prime 6.",
      "Essa base mantém a temperatura estável durante o serviço. Por cima, firelogs para a chama.",
      "Esta combinação pode reduzir a lenha necessária no serviço, porque o chef deixa de depender só do calor da lenha queimada.",
      "Alguns operadores de pizza usam a base de carvão e acrescentam um toro ou meio toro para manter o fogo. Assim eliminam a dependência de lenha inconsistente, libertam armazenamento e, sobretudo, controlam o food cost.",
    ],
    anywhere: "Onde houver fogo",
  },
  sampleForm: {
    kicker: "Pedir amostra",
    title: "Amostra GRÁTIS",
    steps: ["Qualificar", "Detalhes"],
    nextTitle: "O que acontece a seguir",
    next: [
      "Amostras disponíveis apenas para profissionais da hotelaria ou de compras.",
      "Empresas de foodservice e hotelaria podem receber uma amostra grátis da Prime 6 para experimentar.",
      "Preencha o formulário e enviaremos uma amostra.",
    ],
    eligibleQ: "Trabalha em hotelaria ou compras?",
    eligibleYes: "Sim — profissional de hotelaria ou compras",
    eligibleNo: "Não — esta amostra não é para mim",
    blocked: "Amostras disponíveis apenas para profissionais da hotelaria ou de compras.",
    equipment: "Aplicação / equipamento",
    equipmentOptions: [
      "Grelha a lenha",
      "Grillworks/J&R/Grills by Demant",
      "Forno de pizza",
      "Forno a carvão (MiBrassa/Josper/Kopa)",
      "Hibachi/Yakitori",
      "Lareira",
      "Tandoor",
      "Outro",
    ],
    fuelsQ: "Que combustíveis usa hoje?",
    fuels: ["Carvão", "Lenha", "Ambos"],
    samplesQ: "Que amostras precisa?",
    samples: ["Carvão", "Lenha", "Ambos"],
    continue: "Continuar",
    back: "Voltar",
    first: "Nome",
    last: "Apelido",
    email: "Email",
    phone: "Telefone",
    restaurant: "Nome do restaurante",
    url: "URL do negócio (site, etc.)",
    address: "Envio / morada do restaurante",
    distributors: "Distribuidores preferidos (indique 3 opções)",
    distributorPlaceholders: ["ex. Sysco, US Foods", "ex. Halperns, Baldor", "ex. D'Artagnan, Fortune Fish"],
    submit: "Enviar",
    thanks: "Obrigado pelo envio!",
    required: "Obrigatório",
  },
  terry: {
    kicker: "Ver a entrevista completa",
    title: "Chef Terry Koval",
    lead: "Ouça o vencedor James Beard, Chef Terry Koval, falar de brincar com o fogo e de por que a Prime 6 é o combustível que escolhe.",
    paragraphs: [
      "O Chef Terry Koval é proprietário e chef de The Deer and The Dove e do B-SIDE em Decatur, GA, que abriu com a mulher Jenn em junho de 2019. Os restaurantes eram muito esperados e receberam distinções da Food and Wine e da Eater Atlanta. Koval foi reconhecido com vários prémios, incluindo o Georgia Organics Farmer Champion gold de 2021 até ao presente, o Slow Food Snail of Approval e o James Beard Best Chef Southeast em 2023. Também é recomendado pelo Guia Michelin.",
      "Antes dos seus restaurantes, Koval mudou-se para Atlanta em 2000, começou no Buckhead Diner e depois no Canoe, onde foi Executive Sous Chef. Mais tarde trabalhou no Lobby at TWELVE e no Room at TWELVE, este último com 3 estrelas do The Atlanta Journal-Constitution sob a sua liderança. Em 2010 concebeu o Farm Burger, com reconhecimento nacional. Em 2013 tornou-se Executive Chef no Wrecking Bar Brewpub, com 3 de 4 estrelas do The Atlanta Journal-Constitution e vários prémios. Koval também apareceu no Food Network em \"Diners, Drive-Ins, and Dives\" e \"Chopped.\"",
      "Koval apoia organizações locais como a Georgia Organics e a Slow Food Atlanta, e vive em Decatur, GA, com a família.",
    ],
  },
  news: {
    kicker: "ABC's Shark Tank",
    title: "Veja a Prime 6 no Shark Tank",
    lead: "Veja como os fundadores da Prime 6 fecharam o acordo com o Shark Kevin O'Leary na temporada 12, episódio 6",
    videos: [
      { title: "Shark Tank Update 2025", time: "02:52" },
      { title: "Shark Tank Short", time: "02:07" },
      { title: "Prime 6 on Shark Tank", time: "10:20" },
      { title: "Shark Tank Update 2021", time: "02:05" },
    ],
    source: "Nas notícias",
  },
  sustain: {
    kicker: "Veritree",
    title: "Painel de sustentabilidade",
    prompt: "Introduza o número de caixas usadas para calcular o seu impacto positivo",
    disclaimer:
      "As métricas e estatísticas apresentadas nesta página baseiam-se em cálculos médios derivados de dados e investigação científica publicamente disponíveis. Estes valores destinam-se apenas a informação, para uma compreensão geral de potenciais impactos ambientais. Os valores são aproximados e podem não representar com precisão condições específicas ou locais. A Prime 6 não garante a exatidão, fiabilidade ou integridade dos dados e declina qualquer responsabilidade por decisões tomadas com base nesta informação.",
    hub: "Visitar o Impact Hub",
    live: "Painel de sustentabilidade",
  },
  contact: {
    kicker: "Contacte-nos",
    title: "Contacte-nos",
    lead: "Dúvidas sobre os produtos Prime 6? Deixe uma mensagem e entraremos em contacto.",
    first: "Nome",
    last: "Apelido",
    email: "Email",
    message: "Mensagem",
    send: "Enviar",
    thanks: "Obrigado pelo envio!",
    company: "Heatman Charcoal LLC",
    address: ["24 Phillips Lane", "Fairmont, WV 26554"],
    phoneLabel: "Telefone",
    phone: "9296761083",
  },
};
